#
# Module manifest for module 'PSvLIMessage'
#
# Generated by: Markus Kraus
#
# Generated on: 01-06-2016
#

@{
  RootModule        = 'PSvLIMessage.psm1'
  ModuleVersion     = '1.0.2'
  GUID              = '2178ce2b-74f6-48ad-83ef-8e6bc37b5606'
  Author            = 'Markus Kraus'
  CompanyName       = 'mycloudrevolution'
  Copyright         = '(c) 2016 Markus Kraus. All rights reserved.'
  Description       = 'PSvLIMessage allows you to Push Messages to VMware vRealize LogInsight via API '
  PowerShellVersion = '3.0'
  FunctionsToExport = 'Push-vLIMessage'
  CmdletsToExport   = ''
  VariablesToExport = ''
  AliasesToExport   = ''
  PrivateData = @{
      PSData = @{
        Tags          = 'VMware', 'vRealize', 'LogInsight', 'REST', 'API'
        LicenseUri    = 'https://github.com/mycloudrevolution/LogInsight-PushMessage/LICENSE'
        ProjectUri    = 'https://github.com/mycloudrevolution/LogInsight-PushMessage/'
        IconUri       = ''
        ReleaseNotes  = ''
    }
  } 
}